#!/bin/sh
set -e

solr_patch() {
  /bin/cp /etc/odn-solr/solr.xml /etc/solr/solr.xml
}

jetty_patch() {
  /bin/cp /etc/odn-solr/jetty-env.sh /etc/default/jetty
}

jetty_restart() {
  /usr/sbin/service jetty restart
}

case "$1" in
  configure)
    solr_patch
    jetty_patch
    jetty_restart
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "$0 called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
